print(':'*80)
print(':'*80)
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*20 + 'WELCOME TO THE KITTIKHUN GAS STATION' + ' '*20 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print('::' + ' '*76 + '::')
print(':'*80)
print(':'*80)
y = 1
while True:
    if y == 1:
        print(':'*80)
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*30 + 'Oil price today' + ' '*31 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '1.Gasoline 95 price 29.19 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '2.Gasoline 91 price 25.30 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '3.Gasohol  91 price 21.68 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '4.Gasohol E20 price 20.20 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '5.Gasohol  95 price 21.20 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '6.Diesel      price 21.10 Baht' + ' '*22 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print(':'*80)
        print(':'*80)
        o = 0
        while not (o in ['1','2','3','4','5','6']) :
                f = input(
                 "Which type of fuel do you want to choose?  :   \n Want to choose  =>>> :   ")
                o = f

        print(':'*80)
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*23 + 'Choose a method of kicking money' + ' '*21 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*24 + '1.Price reduced in liters' + ' '*27 + '::')
        print('::' + ' '*24 + '2.The number of liters is the price' + ' '*17 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print('::' + ' '*76 + '::')
        print(':'*80)
        print(':'*80)
        l1 = 0
        status = True
        a = 0
        while not (l1 in ['1','2']) :
                if l1 in ['1','2'] and status == True :
                        status = True
                else :
                    status = False
                    if a > 0 :
                        print('new choose')
                a+=1
                l1 = input("Which one do you want to choose? : \n Want to choose   =>>>  : ")
                e = l1                
        if "1" in e:
            n1 = input(" Amount to be entered     \n Money entered  =>>> :   ")
            g1 = int(n1)

        elif "2" in e:
            n2 = input(
                " Required number of liters     \n Number of liters put  =>>> :   ")
            g2 = int(n2)

        if "1" in e:
            if '1' in f:
                u = (g1 / 29.16)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '2' in f:
                u = (g1 / 25.30)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)


            elif '3' in f:
                u = (g1 / 21.68)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '4' in f:
                u = (g1 / 20.2)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '5' in f:
                u = (g1 / 21.2)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '6' in f:
                u = (g1 / 21.1)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + 'Amount of fuel =>>:','%.2f' % u,'liters' + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            else:
                print("The information is incorrect, please check again")

        elif "2" in e:

            if '1' in f:
                u = (g2 * 29.16)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '2' in f:
                u = (g2 * 25.30)
                print(
                    ':'*80)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '3' in f:
                u = (g2 * 21.68)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '4' in f:
                u = (g2 * 20.2)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '5' in f:
                u = (g2 * 21.2)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            elif '6' in f:
                u = (g2 * 21.1)
                print(':'*80)
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*20 + "Total amount :  ", '%.2f' %u, "Baht " + ' '*24 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print('::' + ' '*76 + '::')
                print(':'*80)

            else:
                print("The information is incorrect, please check again")

            x = int(input("Chose 1 for to work  Chose 0 for Stop working\n"))
            y = x
    elif y == 0:
        print(" Stop working ")
        break
